@startuml
'https://plantuml.com/class-diagram

class Model{
- dessinClasses : ArrayList<DessinClasse>
+ ajoutClasse(s : String) : void
}

class ControleurSelection{
- model : Model
+ ControleurSelection(model : Model)
+ handle(m : MouseEvent) : void
}

ControleurSelection -> Model
@enduml