@startuml
'https://plantuml.com/sequence-diagram

participant Main
participant vueAfficheur
participant Tree

activate Main

Main -> vueAfficheur **
activate vueAfficheur
vueAfficheur -> Tree
activate Tree
vueAfficheur <-- Tree
deactivate Tree
Main <-- vueAfficheur
deactivate vueAfficheur
deactivate Main

@enduml